--MSSV    : 19522534
--HOTEN   : Nguyễn Công Vũ
--DE	  : Đề 4
--NGAY THI: 26/12/2020

----------------------------------------------------------------------------------------------------------------------------
--<CAU 1>: 
SELECT NB.MANB, NB.HOTEN, NB.DIACHI FROM  NGUOI_BAN NB INNER JOIN PHIEU_DANG_KY P ON NB.MANB = P.MANB
WHERE MONTH(NGAYDK) = 10 AND YEAR(NGAYDK) = 2006 

--</CAU 1>
----------------------------------------------------------------------------------------------------------------------------
--<CAU 2>:
SELECT NB.HOTEN, PD.NGAYDK, MAX (DAY(PG.DENNGAY - PG.TUNGAY)) AS SONGAYGIAHANLAUNHAT FROM NGUOI_BAN NB, PHIEU_DANG_KY PD, PHIEU_GIA_HAN PG
WHERE NB.MANB = PD.MANB AND PG.MAPDK = PD.MAPDK
GROUP BY NB.HOTEN, PD.NGAYDK

--</CAU 2>
----------------------------------------------------------------------------------------------------------------------------
--<CAU 3>:
SELECT NB.MANB, NB.HOTEN, NB.DIACHI FROM NGUOI_BAN NB, PHIEU_DANG_KY PD, CT_PDK CT
WHERE NB.MANB = PD.MANB AND PD.MAPDK = CT.MAPDK 
GROUP BY NB.MANB, NB.HOTEN, NB.DIACHI
HAVING COUNT(DISTINCT CT.MADV) = (SELECT COUNT(*) FROM DICH_VU)

--</CAU 3>
----------------------------------------------------------------------------------------------------------------------------
--<CAU 4>:
--BANG TAM ANH HUONG:
--PHIEU_DANG_KY (THÊM +(TONGSODV), XÓA -, SỬA +(TONGSODV))
--CT_PDK (THÊM +(MADV), XÓA -(MADV), SỬA -)

--XU LI TREN BANG PHIEU_DANG_KY
--TRIGGER THEM, SUA
CREATE TRIGGER TRG_PHIEUDANGKY_TONGSODV ON PHIEU_DANG_KY
FOR INSERT, UPDATE
AS 
BEGIN
	DECLARE @MAPDK CHAR(10), @TONGSODV_PDK INT, @TONGSODV_CTPDK INT
	SELECT @TONGSODV_PDK = TONGSODV, @MAPDK = MAPDK FROM INSERTED
	SELECT @TONGSODV_CTPDK = COUNT(DISTINCT MADV) FROM CT_PDK WHERE MAPDK = @MAPDK
	IF @TONGSODV_PDK = @TONGSODV_CTPDK 
		PRINT'THANH CONG'
	ELSE
		BEGIN
			PRINT'LOI! KHONG HOP LE'
			ROLLBACK TRAN
		END
END
-- XU LI TREN BANG CT_PDK
-- TRIGGER THEM
CREATE TRIGGER TRG_INS_CTPDK_MADV ON CT_PDK
FOR INSERT
AS
BEGIN
	DECLARE @MAPDK CHAR(10), @TONGSODV_PDK INT, @TONGSODV_CTPDK INT
	SELECT @MAPDK = MAPDK FROM INSERTED
	SELECT @TONGSODV_CTPDK = COUNT(DISTINCT MADV) FROM CT_PDK WHERE MAPDK = @MAPDK
	SELECT @TONGSODV_PDK FROM PHIEU_DANG_KY WHERE MAPDK = @MAPDK
	IF @TONGSODV_PDK = @TONGSODV_CTPDK
		PRINT'THANH CONG'
	ELSE
		BEGIN
			PRINT'LOI! KHONG HOP LE'
			ROLLBACK TRAN
		END
END

--TRIGGER XOA
CREATE TRIGGER TRG_DEL_CTPKD_MADV ON CT_PDK
FOR DELETE
AS
BEGIN
	DECLARE @MAPDK CHAR(10), @TONGSODV_PDK INT, @TONGSODV_CTPDK INT
	SELECT @MAPDK = MAPDK FROM DELETED
	SELECT @TONGSODV_CTPDK = COUNT(DISTINCT MADV) FROM CT_PDK WHERE MAPDK = @MAPDK
	SELECT @TONGSODV_PDK = TONGSODV FROM PHIEU_DANG_KY WHERE MAPDK = @MAPDK
	IF @TONGSODV_PDK = @TONGSODV_CTPDK
		PRINT'THANH CONG'
	ELSE
		BEGIN
			PRINT'LOI! KHONG HOP LE'
			ROLLBACK TRAN
		END
END
--</CAU 4>
CREATE DATABASE QLDD

CREATE TABLE PHIEU_DANG_KY(
	TONGSODV INT,
	MAPDK CHAR(10)
)

CREATE TABLE CT_PDK(
	MADV INT,
	MAPDK CHAR(10)
)