-- TAO DATABASE QLGV
CREATE DATABASE QLGV
GO
USE QLGV
-- TAO CAC BANG VA KHOA CHINH
CREATE TABLE KHOA(
	MAKH VARCHAR(4),
	TENKH VARCHAR(20),
	NGTLAP SMALLDATETIME,
	TRKH CHAR(4),
	CONSTRAINT PK_KHOA PRIMARY KEY(MAKH)
)

CREATE TABLE MONHOC(
	MAMH VARCHAR(10),
	TENMH VARCHAR(40),
	TCLT TINYINT,
	TCTH TINYINT,
	MAKH VARCHAR(4),
	CONSTRAINT PK_MONHOC PRIMARY KEY(MAMH)
)

CREATE TABLE DIEUKIEN(
	MAMH VARCHAR(10),
	MAMH_TRUOC VARCHAR(10),
	CONSTRAINT PK_DIEUKINE PRIMARY KEY(MAMH, MAMH_TRUOC)
)

CREATE TABLE GIAOVIEN(
	MAGV CHAR(4),
	HOTEN VARCHAR(40),
	HOCVI VARCHAR(10),
	HOCHAM VARCHAR(10),
	GIOITINH VARCHAR(3),
	NGSINH SMALLDATETIME,
	NGVL SMALLDATETIME,
	HESO NUMERIC(4, 2),
	MUCLUONG MONEY,
	MAKH VARCHAR(4),
	CONSTRAINT PK_GIAOVIEN PRIMARY KEY(MAGV)
)


CREATE TABLE LOP(
	MALOP CHAR(3),
	TENLOP VARCHAR(40),
	TRLOP CHAR(5),
	SISO TINYINT,
	MAGVCN CHAR(4), 
	CONSTRAINT PK_LOP PRIMARY KEY(MALOP)
)

CREATE TABLE HOCVIEN(
	MAHV CHAR(5),
	HO VARCHAR(10),
	TEN VARCHAR(10),
	NGSINH SMALLDATETIME,
	GIOITINH VARCHAR(3),
	NOISINH VARCHAR(40), 
	MALOP CHAR(3), 
	CONSTRAINT PK_HOCVIEN PRIMARY KEY(MAHV)
)

CREATE TABLE GIANGDAY(
	MALOP CHAR(3),
	MAMH VARCHAR(10),
	MAGV CHAR(4),
	HOCKY TINYINT,
	NAM SMALLINT,
	TUNGAY SMALLDATETIME,
	DENNGAY SMALLDATETIME,
	CONSTRAINT PK_GIANGDAY PRIMARY KEY(MALOP, MAMH)
)

CREATE TABLE KETQUATHI(
	MAHV CHAR(5),
	MAMH VARCHAR(10),
	LANTHI TINYINT,
	NGTHI SMALLDATETIME,
	DIEM NUMERIC(4, 2),
	KETQUA VARCHAR(10),
	CONSTRAINT PK_KETQUATHI PRIMARY KEY(MAHV, MAMH, LANTHI)
)
-- PHAN 1
-- CAU 1 
-- TAO KHOA NGOAI VA KHOA CHINH (DA TAO O TREN)
ALTER TABLE GIAOVIEN
ADD CONSTRAINT FK_GIAOVIEN
FOREIGN KEY (MAKH) REFERENCES KHOA(MAKH)

--FIX 
ALTER TABLE KHOA 
ADD CONSTRAINT FK_KHOA
FOREIGN KEY (TRKH) REFERENCES GIAOVIEN(MAGV)
ALTER TABLE KHOA
DROP CONSTRAINT FK_KHOA

ALTER TABLE MONHOC
ADD CONSTRAINT FK_MONHOC
FOREIGN KEY (MAKH) REFERENCES KHOA(MAKH)

ALTER TABLE LOP
ADD CONSTRAINT FK_LOP_MAGVCN
FOREIGN KEY (MAGVCN) REFERENCES GIAOVIEN(MAGV)

-- FIX
ALTER TABLE LOP
ADD CONSTRAINT FK_LOP_TRLOP
FOREIGN KEY (TRLOP) REFERENCES HOCVIEN(MAHV)
ALTER TABLE LOP
DROP CONSTRAINT FK_LOP_TRLOP

ALTER TABLE  GIANGDAY
ADD CONSTRAINT FK_GIANGDAY_MAMH
FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)

ALTER TABLE GIANGDAY
ADD CONSTRAINT FK_GIANGDAY_MAGV
FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV)

ALTER TABLE GIANGDAY
ADD CONSTRAINT FK_GIANGDAY_MALOP
FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)

ALTER TABLE DIEUKIEN
ADD CONSTRAINT FK_DIEUKIEN_MAMH
FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)

ALTER TABLE DIEUKIEN
ADD CONSTRAINT FK_DIEUKIEN_MAMHTRUOC
FOREIGN KEY (MAMH_TRUOC) REFERENCES MONHOC(MAMH)

ALTER TABLE KETQUATHI
ADD CONSTRAINT FK_KETQUATHI_MAHV
FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV)

ALTER TABLE KETQUATHI
ADD CONSTRAINT FK_KETQUATHI_MAMH
FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)

ALTER TABLE HOCVIEN
ADD CONSTRAINT FK_HOCVIEN
FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)

-- THEM 3  COLUMN GHICHU, DIEMTB, XEP LOAI

ALTER TABLE HOCVIEN
ADD GHICHU VARCHAR(10)

ALTER TABLE HOCVIEN
ADD DIEMTB NUMERIC(4, 2)

ALTER TABLE HOCVIEN
ADD XEPLOAI VARCHAR(10)


-- CAU 2 DA CO SAN KHI TAO TABLE
-- CAU 3
ALTER TABLE GIAOVIEN
ADD CONSTRAINT CHK_GIAOVIEN_GIOITINH
CHECK (GIOITINH IN ('Nam', 'Nu'))

ALTER TABLE HOCVIEN
ADD CONSTRAINT CHK_HOCVIEN_GIOITINH
CHECK (GIOITINH IN ('Nam', 'Nu'))

-- CAU 4
ALTER TABLE KETQUATHI
ALTER COLUMN DIEM NUMERIC(4, 2)

-- CAU 5
ALTER TABLE KETQUATHI
ADD CONSTRAINT CHK_KETQUATHI_DAT
CHECK (DIEM >= 5 AND KETQUA = 'Dat')

ALTER TABLE KETQUATHI
ADD CONSTRAINT CHK_KETQUATHI_KHONGDAT
CHECK (DIEM < 5 AND KETQUA = 'Khong Dat')

-- CAU 6
ALTER TABLE KETQUATHI
ADD CONSTRAINT CHK_KETQUATHI_LANTHI
CHECK (LANTHI <= 3)

-- CAU 7
ALTER TABLE GIANGDAY
ADD CONSTRAINT CHK_GIANGDAY_HOCKY
CHECK (HOCKY >= 1 AND HOCKY <= 3)

-- CAU 8
ALTER TABLE GIAOVIEN
ADD CONSTRAINT CHK_GIANGDAY_HOCVI
CHECK (HOCVI IN ('CN', 'KS', 'THS', 'TS', 'PTS'))

-- CAU 9, CAU 10 ...

-- CAU 11
ALTER TABLE HOCVIEN
ADD CONSTRAINT CHK_HOCVIEN_AGE
CHECK (YEAR(GETDATE())  - YEAR(NGSINH) >= 18)

-- CAU 12
ALTER TABLE GIANGDAY
ADD CONSTRAINT CHK_GIANGDAY_DAY
CHECK (TUNGAY < DENNGAY)

-- CAU 13
ALTER TABLE GIAOVIEN
ADD CONSTRAINT CHK_GIAOVIEN_AGE
CHECK (YEAR(NGVL) - YEAR(NGSINH) >= 22)

-- CAU 14
ALTER TABLE MONHOC
ADD CONSTRAINT CHK_MONHOC_TINCHI
CHECK (ABS(TCLT - TCTH) <= 3)

/*IMPORT DU LIEU TU BANG EXCEL*/
-----------------------------------BAI TH3-----------------------------------
-- PHAN 2
-- CAU 1 
UPDATE GIAOVIEN
SET HESO = HESO + 0.2
WHERE MAGV IN (SELECT TRKH FROM KHOA)

-- CAU 2 
UPDATE HOCVIEN
SET DIEMTB = (SELECT AVG(DIEM) FROM KETQUATHI K1 
					WHERE LANTHI = (SELECT MAX(LANTHI) FROM KETQUATHI K2 
					GROUP BY MAHV, MAMH 
					HAVING K1.MAHV = K2.MAHV AND K1.MAMH = K2.MAMH)
			GROUP BY MAHV
			HAVING HOCVIEN.MAHV = MAHV
)

-- CAU 3
UPDATE HOCVIEN 
SET GHICHU = 'Cam thi' 
WHERE MAHV IN (SELECT MAHV FROM KETQUATHI
GROUP BY MAHV, MAMH 
HAVING MAX(LANTHI) = 3  AND MAX(DIEM) < 5)

-- CAU 4
UPDATE HOCVIEN	
SET XEPLOAI = CASE
	WHEN DIEMTB >= 9 THEN 'XS'
	WHEN DIEMTB >= 8 AND DIEMTB < 9 THEN 'G'
	WHEN DIEMTB >= 6.5 AND DIEMTB < 8 THEN 'K'
	WHEN DIEMTB >= 5 AND DIEMTB < 6.5 THEN 'TB'
	WHEN DIEMTB < 5 THEN 'Y'
END
	

-- PHAN 3
-- CAU 1 
SELECT HV.MAHV, HV.HO, HV.TEN, HV.NGSINH, HV.MALOP FROM HOCVIEN HV, LOP L 
WHERE L.MALOP = HV.MALOP AND L.TRLOP = HV.MAHV

-- CAU 2
SELECT DISTINCT HV.MAHV, (HV.HO + ' ' + HV.TEN) AS HOTEN , KQ.LANTHI, KQ.DIEM FROM HOCVIEN HV, KETQUATHI KQ 
WHERE LEFT(KQ.MAHV, 3) = 'K12' AND HV.MAHV = KQ.MAHV

-- CAU 3
SELECT DISTINCT HV.MAHV, KQ.MAMH, HV.HO, HV.TEN FROM HOCVIEN HV, KETQUATHI KQ 
WHERE KQ.LANTHI = '1' AND KQ.KETQUA = 'Dat' AND HV.MAHV = KQ.MAHV

-- CAU 4
SELECT HV.MAHV, HV.HO, HV.TEN FROM HOCVIEN HV, KETQUATHI KQ 
WHERE LEFT(KQ.MAHV, 3) = 'K11' AND KQ.MAMH = 'CTRR' AND KQ.LANTHI = '1'
AND KQ.KETQUA = 'Khong Dat' AND HV.MAHV = KQ.MAHV

--CAU 5
SELECT HV.MAHV, HV.HO, HV.TEN FROM HOCVIEN HV INNER JOIN KETQUATHI K ON HV.MAHV = K.MAHV
WHERE K.MAMH = 'CTRR'
AND K.LANTHI = (SELECT MAX(LANTHI) FROM KETQUATHI K1 WHERE K1.MAMH = 'CTRR' GROUP BY K1.MAHV HAVING K.MAHV = K1.MAHV)
AND K.KETQUA = 'Khong Dat'
GROUP BY HV.MAHV, HV.HO, HV.TEN

-----------------------------------BAI TH3-----------------------------------
-- CAU 6
SELECT DISTINCT GD.MAMH FROM GIAOVIEN GV, GIANGDAY GD
WHERE GD.HOCKY = '1' AND GD.NAM = '2006' AND GD.MAGV = GV.MAGV AND GV.HOTEN = 'Tran Tam Thanh'

-- CAU 7
SELECT DISTINCT GD.MAMH, MH.TENMH FROM GIAOVIEN GV, GIANGDAY GD, LOP L, MONHOC MH
WHERE GD.HOCKY = '1' AND GD.NAM = '2006' AND GD.MAMH = MH.MAMH AND L.MALOP = 'K11' AND L.MAGVCN = GD.MAGV

-- CAU 8
SELECT HV.HO, HV.TEN FROM HOCVIEN HV, GIANGDAY GD, GIAOVIEN GV, MONHOC MH, LOP L
WHERE GV.MAGV = GD.MAGV AND GV.HOTEN = 'Nguyen To Lan' AND MH.MAMH = GD.MAMH
AND MH.TENMH = 'Co so du lieu' AND GD.MALOP = L.MALOP AND L.TRLOP = HV.MAHV

-- CAU 9
/*c1*/
SELECT DK.MAMH_TRUOC, MH.TENMH FROM MONHOC MH, DIEUKIEN DK WHERE(DK.MAMH = 'CSDL' AND DK.MAMH_TRUOC = MH.MAMH)
/*c2*/
SELECT DK.MAMH_TRUOC, (SELECT TENMH FROM MONHOC A WHERE DK.MAMH_TRUOC = A.MAMH) AS TENMH 
FROM MONHOC MH INNER JOIN DIEUKIEN DK ON MH.MAMH = DK.MAMH 
WHERE MH.TENMH = 'Co so du lieu'

-- CAU 10
SELECT DK.MAMH, (SELECT TENMH FROM MONHOC A WHERE DK.MAMH = A.MAMH ) AS TENMH 
FROM MONHOC MH INNER JOIN DIEUKIEN DK ON MH.MAMH = DK.MAMH_TRUOC 
WHERE MH.TENMH = 'Cau truc roi rac'

-- CAU 11
SELECT GV.HOTEN FROM (GIAOVIEN GV INNER JOIN GIANGDAY GD ON GV.MAGV = GD.MAGV) INNER JOIN MONHOC MH ON MH.MAMH = GD.MAMH
WHERE GD.MALOP = 'K11' AND GD.HOCKY = '1' AND GD.NAM = '2006' AND MH.TENMH = 'Cau truc roi rac'
AND EXISTS (SELECT * FROM GIANGDAY A WHERE GD.MAGV = A.MAGV AND MH.TENMH = 'Cau truc roi rac' AND A.MALOP = 'K12' AND A.HOCKY = '1' AND A.NAM = '2006')

-- Cau 12
SELECT HV.HO, HV.TEN FROM HOCVIEN HV INNER JOIN KETQUATHI K ON HV.MAHV = K.MAHV
WHERE K.MAMH = 'CSDL' AND K.LANTHI = '1'AND K.KETQUA = 'Khong Dat'
EXCEPT
SELECT HV.HO, HV.TEN FROM HOCVIEN HV INNER JOIN KETQUATHI K ON HV.MAHV = K.MAHV
WHERE K.MAMH = 'CSDL' AND K.LANTHI = '2'

-- CAU 13
SELECT MAGV, HOTEN FROM GIAOVIEN 
WHERE MAGV NOT IN (SELECT MAGV FROM GIANGDAY)

-- CAU 14
SELECT DISTINCT GV.MAGV, GV.HOTEN FROM (GIAOVIEN GV INNER JOIN GIANGDAY GD ON GV.MAGV = GD.MAGV) INNER JOIN MONHOC MH ON MH.MAMH = GD.MAMH
WHERE GV.MAGV IN (SELECT MAGV FROM GIANGDAY) AND MH.MAKH != GV.MAKH

-- CAU 15
SELECT HV.HO, HV.TEN FROM HOCVIEN HV INNER JOIN KETQUATHI K ON HV.MAHV = K.MAHV
WHERE (HV.MALOP = 'K11' AND K.LANTHI = '3' AND K.KETQUA = 'Khong Dat') 
UNION
SELECT HV.HO, HV.TEN FROM HOCVIEN HV INNER JOIN KETQUATHI K ON HV.MAHV = K.MAHV
WHERE (HV.MALOP = 'K11' AND K.MAMH = 'CTRR' AND K.LANTHI = '2' AND K.DIEM = '5')  

-- CAU 16
SELECT GV.HOTEN FROM GIAOVIEN GV INNER JOIN GIANGDAY GD ON GV.MAGV = GD.MAGV
WHERE GD.MAMH = 'CTRR' 
GROUP BY GV.HOTEN
HAVING COUNT(*) >= 2 AND SUM(GD.HOCKY) % 2 = 0 AND SUM(GD.NAM) % 2 =0 

-- CAU 17 
SELECT HV.HO, HV.TEN, K1.DIEM FROM KETQUATHI K1 INNER JOIN HOCVIEN HV ON K1.MAHV = HV.MAHV 
WHERE LANTHI = (SELECT MAX(LANTHI) FROM KETQUATHI K2 WHERE MAMH = 'CSDL'
GROUP BY MAHV, MAHV HAVING K1.MAHV = K2.MAHV) AND MAMH  = 'CSDL'

-- CAU 18
SELECT HV.HO, HV.TEN, MAX(DIEM) AS DIEM FROM HOCVIEN HV INNER JOIN KETQUATHI K ON HV.MAHV = K.MAHV	
WHERE K.MAMH = 'CSDL'
GROUP BY HV.HO, HV.TEN

---------------------------------------KET THUC BAI TH3---------------------------------------
-- CAU 19
SELECT TOP 1 NGTLAP FROM KHOA
ORDER BY NGTLAP ASC

-- CAU 20
SELECT COUNT(HOCHAM) AS SOLUONGGV FROM GIAOVIEN WHERE HOCHAM IN ('GS', 'PGS')

-- CAU 21
SELECT HOCVI, COUNT(*) AS SOLUONG FROM GIAOVIEN
GROUP BY HOCVI

-- CAU 22
SELECT MAMH, KETQUA, COUNT(MAHV) AS SOLUONG FROM KETQUATHI K
WHERE LANTHI = (SELECT MAX(LANTHI) FROM KETQUATHI K1 GROUP BY MAHV, MAMH HAVING K.MAHV = K1.MAHV AND K.MAMH = K1.MAMH)
GROUP BY MAMH, KETQUA

-- CAU 23
SELECT GV.MAGV, GV.HOTEN FROM GIAOVIEN GV INNER JOIN  LOP L ON GV.MAGV = L.MAGVCN 
WHERE GV.MAGV IN (SELECT GD.MAGV FROM LOP L INNER JOIN GIANGDAY GD ON L.MAGVCN = GD.MAGV
WHERE L.MALOP = GD.MALOP
GROUP BY GD.MAGV
HAVING COUNT(*) >= 1
)

-- CAU 24
SELECT TOP 1 HV.HO,HV.TEN FROM HOCVIEN HV INNER JOIN LOP L ON HV.MAHV = L.TRLOP
ORDER BY SISO DESC 

-- CAU 25

-- CAU 26
SELECT HV.MAHV, HV.HO, HV.TEN FROM HOCVIEN HV INNER JOIN KETQUATHI K ON HV.MAHV = K.MAHV 
WHERE K.DIEM BETWEEN '9' AND '10' 
GROUP BY HV.MAHV, HV.HO, HV.TEN
HAVING COUNT(*) >= ALL (SELECT COUNT(*) FROM HOCVIEN HV1 INNER JOIN KETQUATHI K1 ON HV1.MAHV = K1.MAHV
WHERE K1.DIEM BETWEEN '9' AND '10' GROUP BY HV1.MAHV)

-- CAU 27
SELECT HV.MAHV, HV.HO, HV.TEN FROM HOCVIEN HV INNER JOIN KETQUATHI K ON HV.MAHV = K.MAHV 
WHERE K.DIEM BETWEEN '9' AND '10' 
GROUP BY HV.MAHV, HV.HO, HV.TEN
HAVING COUNT(*) >= ALL (SELECT COUNT(*) FROM HOCVIEN HV1 INNER JOIN KETQUATHI K1 ON HV1.MAHV = K1.MAHV
WHERE K1.DIEM BETWEEN '9' AND '10' GROUP BY HV1.MAHV)
