CREATE DATABASE QLDP
GO
CREATE TABLE NHACUNGCAP(
	MANCC CHAR(5),
	TENNCC VARCHAR(50),
	QUOCGIA VARCHAR(20),
	LOAINCC VARCHAR(20),
	CONSTRAINT PK_NHACUNGCAP PRIMARY KEY(MANCC)
)

CREATE TABLE DUOCPHAM(
	MADP CHAR(4),
	TENDP VARCHAR(50),
	LOAIDP VARCHAR(20),
	GIA MONEY,
	CONSTRAINT PK_DUOCPHAM PRIMARY KEY(MADP)
)

CREATE TABLE PHIEUNHAP(
	SOPN CHAR(5),
	NGAYNHAP SMALLDATETIME,
	MANCC CHAR(5),
	LOAINHAP VARCHAR(20),
	CONSTRAINT PK_PHIEUNHAP PRIMARY KEY(SOPN)
)

CREATE TABLE CTPN(
	SOPN CHAR(5),
	MADP CHAR(4),
	SOLUONG INT,
	CONSTRAINT PK_CTPN PRIMARY KEY(SOPN, MADP)
)
ALTER TABLE PHIEUNHAP
ADD CONSTRAINT FK_PHIEUNHAP_MANCC
FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC)

ALTER TABLE CTPN
ADD CONSTRAINT FK_CTPN_SOPN
FOREIGN KEY (SOPN) REFERENCES PHIEUNHAP(SOPN),
CONSTRAINT FK_CTPN_MADP
FOREIGN KEY (MADP) REFERENCES DUOCPHAM(MADP)

--NHACUNGCAP
INSERT INTO NHACUNGCAP(MANCC, TENNCC, QUOCGIA, LOAINCC)
VALUES('NCC01', 'PHUC HUNG', 'VIET NAM', 'THUONG XUYEN'),
	('NCC02', 'J.B.PHARMACEUTICALS', 'INDIA', 'VANGLAI'),
	('NCC03', 'SAPHARCO', 'SINGAPORE', 'VANGLAI')

--DUOCPHAM
INSERT INTO DUOCPHAM(MADP, TENDP, LOAIDP, GIA)
VALUES('DP01', 'THUOC BO PH', 'SIRO', '120'),
	('DP02', 'ZECUF HERBAL COUCHREMEDT', 'VIEN NEN', '200'),
	('DP03', 'COTRIM', 'VIEN SUI', '80')

--PHIEUNHAP
INSERT INTO PHIEUNHAP(SOPN, NGAYNHAP, MANCC, LOAINHAP)
VALUES('00001', '22/11/2017', 'NCC01', 'NOI DIA'),
	('00002', '04/12/2017', 'NCC03', 'NHAP KHAU'),
	('00003', '10/12/2017', 'NCC02', 'NHAP KHAU')

--CTPN
INSERT INTO CTPN(SOPN, MADP, SOLUONG)
VALUES('00001', 'DP01', '100'),
	('00001', 'DP02', '200'),
	('00003', 'DP03', '543')

--3
GO
CREATE TRIGGER TRG_SIRO ON DUOCPHAM
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @LOAIDP VARCHAR(20), @GIA MONEY
	SELECT @LOAIDP = LOAIDP, @GIA = GIA FROM INSERTED
	IF @LOAIDP = 'SIRO' AND @GIA < 100000
	BEGIN
		PRINT'LOI! KHONG HOP LE'
		ROLLBACK TRAN
	END
	ELSE
	BEGIN
		PRINT'THANH CONG'
	END
END

-- 4
GO
CREATE TRIGGER TRG_LOAINHAP ON PHIEUNHAP
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @QUOCGIA VARCHAR(20), @LOAINHAP VARCHAR(20)
	SELECT @QUOCGIA = QUOCGIA, @LOAINHAP = LOAINHAP FROM INSERTED I INNER JOIN NHACUNGCAP N
	ON I.MANCC = N.MANCC 
	IF @QUOCGIA != 'VIET NAM' AND @LOAINHAP != 'NHAP KHAU'
	BEGIN
		PRINT 'LOI! KHONG HOP LE'
		ROLLBACK TRAN
	END
	ELSE
	BEGIN
		PRINT'THANH CONG'
	END

END

-- 5
SELECT * FROM PHIEUNHAP 
WHERE MONTH(NGAYNHAP) = '12' AND YEAR(NGAYNHAP) = '2017'
ORDER BY NGAYNHAP ASC

-- 6
SELECT D.MADP, D.TENDP FROM DUOCPHAM D INNER JOIN CTPN C ON D.MADP = C.MADP
								INNER JOIN PHIEUNHAP P ON C.SOPN = P.SOPN
WHERE YEAR(NGAYNHAP) = '2017' AND C.SOLUONG >= ALL(SELECT SOLUONG FROM CTPN)								

-- 7
SELECT D.MADP, D.TENDP FROM DUOCPHAM D INNER JOIN CTPN C ON D.MADP = C.MADP
								INNER JOIN PHIEUNHAP P ON C.SOPN = P.SOPN
WHERE MANCC IN (SELECT MANCC FROM NHACUNGCAP WHERE LOAINCC = 'THUONG XUYEN')

-- 8
SELECT N.MANCC, N.TENNCC FROM NHACUNGCAP N INNER JOIN PHIEUNHAP P ON N.MANCC = P.MANCC
											INNER JOIN CTPN C ON P.SOPN = C.SOPN
WHERE YEAR(P.NGAYNHAP) = '2017' AND C.MADP IN (SELECT MADP FROM DUOCPHAM WHERE GIA > 100)
GROUP BY N.MANCC, N.TENNCC
HAVING COUNT(*) = (SELECT COUNT(*) FROM DUOCPHAM D WHERE D.GIA > 100)


								