CREATE DATABASE QLPB
GO
CREATE TABLE EMPLOYEE(
	EMPNO VARCHAR(5),
	EMPNAME VARCHAR(30),
	BIRTHDAY SMALLDATETIME,
	DEPTNO VARCHAR(5),
	MGRNO VARCHAR(5) NOT NULL,
	STARTDATE SMALLDATETIME,
	SALARY MONEY,
	LEVEL INT,
	STATUS INT,
	NOTE VARCHAR(5),
	CONSTRAINT PK_EMPLOYEE PRIMARY KEY(EMPNO),
	CONSTRAINT CHK_LEVEL CHECK(LEVEL BETWEEN 1 AND 7),
	CONSTRAINT CHK_STATUS CHECK(STATUS IN ('0', '1', '2'))
)

CREATE TABLE EMP_SKILL(
	SKILLNO INT,
	EMPNO VARCHAR(5),
	SKILLLEVEL INT,
	REGDATE SMALLDATETIME,
	DESCRIPTION VARCHAR(50),
	CONSTRAINT PK_EMP_SKILL PRIMARY KEY(SKILLNO, EMPNO),
	CONSTRAINT CHK_SKILLLEVEL CHECK(SKILLLEVEL BETWEEN 1 AND 3),
	CONSTRAINT FK_EMP_SKILL FOREIGN KEY(EMPNO) REFERENCES EMPLOYEE(EMPNO)
)

CREATE TABLE SKILL(
	SKILLNO INT IDENTITY(1, 1), 
	SKILLNAME VARCHAR(20),
	NOTE VARCHAR(50),
	CONSTRAINT PK_SKILL PRIMARY KEY(SKILLNO)
)

CREATE TABLE DEPARTMENT(
	DEPTNO VARCHAR(5),
	DEPTNAME VARCHAR(20),
	NOTE VARCHAR(50),
	CONSTRAINT PK_DEPARTMENT PRIMARY KEY(DEPTNO)
)
-- 2
-- A
ALTER TABLE EMPLOYEE
ADD EMAIL VARCHAR(5) UNIQUE
-- B
ALTER TABLE EMPLOYEE
ALTER MGRNO BIT DEFAULT 0

-- 3
-- A
ALTER TABLE EMPLOYEE 
ADD CONSTRAINT FK_EMPLOYEE
FOREIGN KEY(DEPTNO) REFERENCES DEPARTMENT(DEPTNO)
-- B
ALTER TABLE EMP_SKILL
DROP COLUMN DESCRIPTION 

-- 4
-- A
-- B
GO
CREATE VIEW EMPLOYEE_TRACKING AS
SELECT EMPNO, EMPNAME FROM EMPLOYEE WHERE LEVEL BETWEEN 3 AND 5


